name: .NET Core
env:
  SONGLIST_REPO_SUBFOLDER:  songlistGeneratorRepo
  SPIEWNIK_REPO_SUBFOLDER:  spiewnikRepo
  SONGLIST_REPO:  $GITHUB_WORKSPACE/songlistGeneratorRepo
  SPIEWNIK_REPO: $GITHUB_WORKSPACE/spiewnikRepo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
      with:
        path: $SONGLIST_REPO_SUBFOLDER
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore -s $SONGLIST_REPO
    - name: Build
      run: dotnet build $SONGLIST_REPO/SonglistGenerator.sln --configuration Release --no-restore
    - name: Checkout spiewnik
      uses: actions/checkout@v2.3.1
      with:
        repository: qamil95/spiewnik
        path: $SPIEWNIK_REPO_SUBFOLDER
    - name: Run SonglistGenerator without parameters
      run: dotnet  $SONGLIST_REPO/SonglistGenerator/bin/Release/netcoreapp3.1/SonglistGenerator.dll
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: SonglistGenerator r${{github.run_number}}
      # Directory containing files to upload
        path: $SONGLIST_REPO_SUBFOLDER/SonglistGenerator/bin/Release/netcoreapp3.1/SonglistGenerator.dll
      
